# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 16:31
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='author',
            field=models.CharField(default='asdf', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='repository',
            name='url',
            field=models.URLField(validators=[app.models.validate_url]),
        ),
    ]
