# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170509_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='author',
        ),
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
